### ISSUE TITLE
Testing replacing Crystal Linux with Arch Linux

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/vanilla-apx-configs#3]
...or remove them.

**Comment by CosmicFusion** [comment]
You can use this from PikaOS

It's just a plain archlinux docker image with yay installed: https://github.com/PikaOS-Linux/archlinux-yay


Configs: https://github.com/PikaOS-Linux/pkg-pika-apx-configs/blob/main/pika-apx-configs/usr/share/apx/stacks/arch-linux.yaml

https://github.com/PikaOS-Linux/pkg-pika-apx-configs/blob/main/pika-apx-configs/usr/share/apx/package-managers/yay.yaml

**Comment by mirkobrombin** [comment]
Awesome, we'll take a look thanks
